# permissions for end users to view orbits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: orbit-viewer-role
rules:
- apiGroups:
  - network.kubeorbit.io
  resources:
  - orbits
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - network.kubeorbit.io
  resources:
  - orbits/status
  verbs:
  - get
