# permissions for end users to view serviceroutes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serviceroute-viewer-role
rules:
- apiGroups:
  - network.kubeorbit.io
  resources:
  - serviceroutes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - network.kubeorbit.io
  resources:
  - serviceroutes/status
  verbs:
  - get
